.env.example, src/web/.env.example, src/web/app/page.tsx
Update the web `.env.example` with the required values.
Update the core `.env` with explanations
Add basic empty handling for formatting
---
=> fix: update .env.examples and add basic empty string handling

Makefile
updating make file for windows
---
=> feat: updating make file

.env.example, .gitignore, Makefile, src/web/app/lib/auth.ts, src/web/package-lock.json, src/web/package.json
Code is now connecting to KeyVault and retrieving the secret.
---
=> feat: adding KeyVault stuff

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml, infrastructure/.gitignore, infrastructure/tf-audit/app_insights.tf, infrastructure/tf-audit/config.tf, infrastructure/tf-audit/data.tf, infrastructure/tf-audit/diagnostic_settings_audit.tf, infrastructure/tf-audit/environments/development.tfvars, infrastructure/tf-audit/environments/integration.tfvars, infrastructure/tf-audit/environments/nft.tfvars, infrastructure/tf-audit/log_analytics_workspace.tf, infrastructure/tf-audit/networking.tf, infrastructure/tf-audit/outputs.tf, infrastructure/tf-audit/private_link_scoped_service.tf, infrastructure/tf-audit/providers.tf, infrastructure/tf-audit/rbac.tf, infrastructure/tf-audit/storage.tf, infrastructure/tf-audit/variables.tf
Audit infrastructure rollout.
Succesfully deployed to Development environment:
https://dev.azure.com/nhse-dtos/dtos-participant-manager/_build/results?buildId=15392&view=results
This establishes the infra which will collect and store the logging from the application.
---
=> feat: DTOSS-7457 audit infrastructure

src/web/app/lib/fetchPatientData.ts
Pass a random UUID into the tradeId header for the API calls
---
=> feat: pass a random UUID into the tradeId header for the API calls

src/api/ParticipantManager.API/Functions/PathwayTypeAssignmentFunctions.cs
Remove authorisation function level from backend api
Removal in development to prove working solution, will review whether it needs adding back in
---
=> fix: Remove function level authorisation from backend function

.env.example, src/web/.env.example, src/web/app/components/header.tsx, src/web/instrumentation.ts
- Use the correct aria-label for the header
- Handle missing `.env` variable for Azure Monitor
- Update the example `.env` files
---
=> fix: Fixes for aria-label, missing .env variables and example .env file

src/api/ParticipantManager.Shared/NhsNumberHashingPolicy.cs
Undoing the earlier whitespace change in a shared function, to trigger a CI rebuild of all Docker containers.
---
=> fix: Force Docker images rebuild

sonar-project.properties
Removal of specific folders from sonar analysis
Not all files need to go through sonar analysis and this file is intended to omit them
---
=> fix: Remove some folders from sonar analysis

src/api/ParticipantManager.Shared/Client/CrudApiClient.cs
Triggering devops pipeline to validate docker build
---
=> chore: Testing pipeline Docker build trigger

src/api/ParticipantManager.Shared/Client/CrudApiClient.cs
chore: Modified log statement to trigger the pipeline
---
=> chore: Modified log statement to force pipeline to run

scripts/config/sonar-scanner.properties
Set the sonar scanning properties to be more inclusive
Seeing inconsistent results in the scans
---
=> fix: Update to source scanning settings

src/web/app/components/signInButton.tsx, src/web/app/styles/components/signIn.module.scss
Following a call with the NHS login team; use the correct style and content for the NHS login button
---
=> fix: use the correct style and content for the NHS login button

.github/actions/perform-static-analysis/action.yaml
Introduce location of coverage.xml when running the code scanner
---
=> fix: Update to include coverage file location

src/api/ParticipantManager.API/Functions/EncounterFunctions.cs, src/api/ParticipantManager.API/Functions/EpisodeFunctions.cs, src/api/ParticipantManager.API/Functions/PathwayTypeEnrolmentFunctions.cs
Auth level changes from function to Anonymous 
---
=> feat: Auth level change to Anonymous

src/web/app/components/screeningList.tsx, src/web/app/lib/getEligibility.ts
Fix linting issues to resolve frontend build
---
=> chore: fix linting issues to resolve frontend build

tests/ParticipantManager.API.Tests/ParticipantFunctionsTests.cs, tests/ParticipantManager.Shared.Tests/ParticipantManager.Shared.Tests.csproj
Add unit tests to increase coverage to 100%. 
Update Versionings on sharedTest.csprog
---
=> feat: ParticipantFunction unit tests

.github/dependabot.yaml
Configure dependabot to raise PRs to update NuGet packages on a daily basis.
Regularly updating dependencies is like tidying the codebase’s pantry: it ensures we’re not cooking with expired ingredients. This update helps keep the project secure, compatible, and performant—with thanks to our trusty butler, Dependabot.
---
=> feat: configure dependabot to update nuget packages

src/web/README.md
Correct a bash command in the documentation.
The stated bash command was incorrect and will not work if a developer follows the instructions verbatim.
---
=> fix: correcting bash command in documentation

src/api/ParticipantManager.API/ParticipantManager.API.csproj, src/api/ParticipantManager.API/Program.cs, src/api/ParticipantManager.EventHandler/ParticipantManager.EventHandler.csproj, src/api/ParticipantManager.EventHandler/Program.cs, src/api/ParticipantManager.Experience.API/ParticipantManager.Experience.API.csproj, src/api/ParticipantManager.Experience.API/Program.cs, src/api/ParticipantManager.Shared/Extensions/HostBuilderExtensions.cs, src/api/ParticipantManager.Shared/ParticipantManager.Shared.csproj, tests/ParticipantManager.Shared.Tests/HostBuilderExtensionsTests.cs
Moved Serilog configuration to a shared hostbuilder extension method
Refactoring to reduce code duplication
---
=> refactor: Moved Serilog configuration to a shared hostbuilder extension method

src/api/ParticipantManager.EventHandler/Functions/CreateEnrolmentHandler.cs
Changed the spelling of enrolment in a log statement to the English variant
Consistency
---
=> fix: english spelling of enrolment

.github/workflows/stage-2-test.yaml, scripts/tests/lint.sh, src/web/app/lib/auth.ts, src/web/app/types/auth/index.d.ts, src/web/jest.config.ts
- Run `npm run lint` in the pipeline for the UI
- Fix outstanding linting issues in the UI
- Output Jest coverage report to the `src/web/coverage` folder
---
=> test: add linting to the pipeline, fix issues and output coverage report

src/web/app/lib/fetchPatientData.test.ts
add tests for the fetch patient data functionality
---
=> test: add tests for the fetch patient data functionality

tests/ParticipantManager.Shared.Tests/CorrelationIdMiddlewareTests.cs
Added tests for CorrelationIdMiddleware
The increase code coverage
---
=> test: Added tests for CorrelationIdMiddleware

src/web/app/accessibility-statement/page.tsx, src/web/app/components/breadcrumb.tsx, src/web/app/components/card.tsx, src/web/app/components/footer.tsx, src/web/app/components/header.tsx, src/web/app/components/insetText.tsx, src/web/app/lib/auth.ts
fix SonarQube maintainability and readability issues on the UI code
---
=> fix: fix SonarQube maintainability and readability issues on the UI code

src/api/ParticipantManager.Experience.API/openapi/openapi.yaml
Adds an OpenAPI spec for the Experience API.
Documents contract between API and front-end.
Can be used as a basis for automated tests, and codegen for front-end types/client.
---
=> Nascent OpenAPI spec for Experience API

src/api/ParticipantManager.EventHandler/Functions/CreateEnrolmentHandler.cs, tests/ParticipantManager.EventHandler.Tests/CreateEnrolmentHandlerTests.cs
Updated tests to cover all branches in CreateEnrolmentHandler
To increase code coverage
---
=> test: Updated tests to cover all branches in CreateEnrolmentHandler

src/api/ParticipantManager.API/openapi/openapi.yaml
Added OpenAPI spec for CRUD API
Documentation, aids understanding of the APIs. Draws attention to potential inconsistencies and areas for improvements.
---
=> feat: OpenAPI spec for CRUD API

Makefile, src/api/ParticipantManager.API/Functions/PathwayTypeEnrolmentFunctions.cs, src/api/ParticipantManager.API/Models/PathwayTypeEnrolment.cs, tests/ParticipantManager.API.Tests/ParticipantManager.API.Tests.csproj, tests/ParticipantManager.API.Tests/PathwayTypeEnrolmentFunctionsTests.cs
Added tests for PathwayTypeEnrolmentFunctions class
To increase code coverage
---
=> test: Added tests for PathwayTypeEnrolmentFunctions class

src/api/ParticipantManager.API/Dockerfile, src/api/ParticipantManager.API/Dockerfile.migrations, src/api/ParticipantManager.EventHandler/Dockerfile, src/api/ParticipantManager.Experience.API/Dockerfile
[fix: avoid running Docker containers as priviledged users](https://github.com/NHSDigital/dtos-participant-manager/pull/97/commits/69ebd75eb142a7430cf1a60a0f580b16b95db481)
[fix: avoid recursively copying directories](https://github.com/NHSDigital/dtos-participant-manager/pull/97/commits/e0c2353460fefca9c8c058fb0d0af224bc6bc57b)
[fix: merge the run instructions](https://github.com/NHSDigital/dtos-participant-manager/pull/97/commits/ee07dfa2a1c292628b31d9d36cc6a22aa7adf19d)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR …
=> fix: Docker image security issues

src/api/ParticipantManager.Shared/DataMasking.cs, src/api/ParticipantManager.Shared/NhsNumberHashingPolicy.cs, src/api/ParticipantManager.Shared/NhsNumberRegexMaskOperator.cs, tests/ParticipantManager.API.Tests/Functions/ParticipantFunctionsTests.cs, tests/ParticipantManager.API.Tests/Functions/PathwayTypeEnrolmentFunctionsTests.cs, tests/ParticipantManager.EventHandler.Tests/Functions/CreateEnrolmentHandlerTests.cs, tests/ParticipantManager.Experience.API.Tests/Functions/GetParticipantIdFunctionTests.cs, tests/ParticipantManager.Experience.API.Tests/Functions/PathwayEnrolmentFunctionTests.cs, tests/ParticipantManager.Experience.API.Tests/Functions/ScreeningEligibilityFunctionTests.cs, tests/ParticipantManager.Experience.API.Tests/Services/TokenServiceTests.cs, tests/ParticipantManager.Shared.Tests/Client/CrudApiClientTests.cs, tests/ParticipantManager.Shared.Tests/CorrelationIdMiddlewareTests.cs, tests/ParticipantManager.Shared.Tests/Extensions/HostBuilderExtensionsTests.cs, tests/ParticipantManager.Shared.Tests/NhsNumberRegexMaskOperatorTests.cs
Changed the structure of the test projects to mirror the structure of the namespaces in the system under test.
Test discoverability - developers can more easily find the test classes associated with the classes being amended.
---
=> refactor: test project structure mirrors system under test

src/api/ParticipantManager.API/Data/DesignTimeDbContextFactory.cs, src/api/ParticipantManager.Shared/Client/CrudApiClient.cs, tests/ParticipantManager.Experience.API.Tests/Services/TokenServiceTests.cs, tests/ParticipantManager.Shared.Tests/Client/CrudApiClientTests.cs, tests/ParticipantManager.Shared.Tests/HttpMessageHandlerExtensions.cs
Added extra tests for CrudApiClient
Increase code coverage
---
=> test: Added extra tests for CrudApiClient

src/api/ParticipantManager.Experience.API/Program.cs, src/api/ParticipantManager.Shared/Client/FeatureFlagClient.cs, tests/ParticipantManager.Shared.Tests/Client/FeatureFlagClientTests.cs
Added tests for FeatureFlagClient
To increase code coverage
---
=> test: Added tests for FeatureFlagClient

src/api/ParticipantManager.EventHandler/Program.cs
- Added correlation id middleware to EventHandler
- Correlation id required for tracking related requests
---
=> fix: Added missing correlation id middleware to EventHandler

README.md
Added links to our OpenAPI docs to the Readme.md
Discoverability of documentation
---
=> feat: add swagger doc links to readme.md

src/api/ParticipantManager.API/openapi/openapi.yaml, src/api/ParticipantManager.Experience.API/openapi/openapi.yaml
Data type for some properties exposed by APIs has changed from date time to date.
Encounters have been removed from the API altogether.
Have updated the OpenAPI spec accordingly.
OpenAPI spec should reflect reality.
---
=> fix: update OpenAPI spec to reflect recent changes

scripts/config/sonar-scanner.properties
Removed sonarqube exclusions from sonar-scanner.properties as these are being configured through the SonarQube UI
consistency
---
=> chore: remove sonar exclusions from properties file

src/web/package-lock.json, src/web/package.json
chore: fix the version of ts-jest
---
=> chore: fix the version of ts-jest

src/api/ParticipantManager.API/ParticipantManager.API.csproj, src/api/ParticipantManager.EventHandler/ParticipantManager.EventHandler.csproj, src/api/ParticipantManager.Experience.API/ParticipantManager.Experience.API.csproj, src/api/ParticipantManager.Shared/ParticipantManager.Shared.csproj, tests/ParticipantManager.API.Tests/ParticipantManager.API.Tests.csproj, tests/ParticipantManager.Experience.API.Tests/ParticipantManager.Experience.API.Tests.csproj, tests/ParticipantManager.Shared.Tests/ParticipantManager.Shared.Tests.csproj, tests/TestUtils/TestUtils.csproj
- Removed unused packages
- Moved Microsoft.EntityFrameworkCore.InMemory to ParticipantManager.API.Tests.csproj
- Marked TestUtils.csproj as not a test project
---
=> refactor: Removed unused NuGet packages

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml, .azuredevops/pipelines/cd-infrastructure-dev-core.yaml, infrastructure/tf-core/data.tf, infrastructure/tf-core/diagnostic_settings.tf, infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/integration.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/postgresql.tf, infrastructure/tf-core/variables.tf
Add a Postgres DB: `participant-database`
To be less locked in to Microsoft (via Azure SQL).
Successfully deployed in Dev:
https://dev.azure.com/nhse-dtos/dtos-participant-manager/_build/results?buildId=16835&view=results
---
=> feat: DTOSS-8134 Create Postgres database

.github/workflows/stage-2-test.yaml, README.md, scripts/config/gitleaks.toml, scripts/tests/test.mk, scripts/tests/ui.sh, src/web/.env.tests, src/web/app/components/signInButton.tsx, src/web/e2e/accessibility.test.ts, src/web/e2e/example.spec.ts, src/web/e2e/navigate.test.ts, src/web/package-lock.json, src/web/package.json, src/web/playwright.config.ts
Added Playwright configuration to run in pipeline with some basic tests Introduces a env.tests file to handle tests env variables (the randomly generated auth secret has been ignored from gitleaks). I'd prefer to use the proper [GitHub action for Playwright](https://playwright.dev/docs/ci-intro#setting-up-github-actions) rather than Makefiles in the pipeline; but sticking with conventions for now.
Added some basic accessibility tests using Axe in the Playwright tests.
The intention is to move towards ["BDD" tests](https://vitalets.github.io/playwright-bdd/#/getting-started/write-first-test?id=step-2-create-feature-file)  but this a start.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable …
=> test: add Playwright configuration to run in pipeline with basic tests

.gitleaksignore, scripts/config/gitleaks.toml
Rather than ignoring the whole `.env.tests` file ignore the hash of the secret using the proper format.
---
=> chore: ignore secrets properly in gitleaks

src/api/ParticipantManager.API/Dockerfile, src/api/ParticipantManager.EventHandler/Dockerfile, src/api/ParticipantManager.Experience.API/Dockerfile
chore: give Docker appuser permission to LogFiles folder
---
=> chore: give Docker appuser permission to LogFiles folder

infrastructure/tf-core/environments/development.tfvars
feat: add terraform config for the Flagsmith environment variable in KeyVault
Required for the use of Flagsmith and KeyVault
---
=> feat: add terraform config for the Flagsmith environment variable

.gitleaksignore, src/api/ParticipantManager.API/Dockerfile, src/api/ParticipantManager.EventHandler/Dockerfile, src/api/ParticipantManager.Experience.API/Dockerfile
chore: setup permissions in folders for the Azure functions in Docker
re-ignore a non-secret in `.env.tests`
---
=> chore: setup permissions in folders for the Azure functions in Docker

README.md, scripts/config/pre-commit.yaml
chore: add make config to the docs and remove lint terraform from precommit
---
=> chore: add make config to the docs and remove lint terraform from precommit

src/web/app/error/auth/page.tsx, src/web/app/lib/auth.ts
chore: add an authentication error page
This is to help identify where the error is coming from; previously all errors were handled by the same error page
---
=> chore: add an authentication error page

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml, .azuredevops/pipelines/cd-infrastructure-dev-core.yaml, infrastructure/tf-audit/providers.tf, infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/int.tfvars, infrastructure/tf-core/providers.tf
Moving from:
- Terraform 1.9.2 to 1.11.4
- Terraform azurerm provider 3.112.0 to 4.26
Technical debt reduction
Successfully deployed to:
- [Participant Manager dev audit](https://dev.azure.com/nhse-dtos/dtos-participant-manager/_build/results?buildId=17149&view=results)
- [Participant Manager dev core](https://dev.azure.com/nhse-dtos/dtos-participant-manager/_build/results?buildId=17136&view=results)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do …
=> fix: DTOSS-4537 Update terraform and azurerm provider versions

src/web/package-lock.json, src/web/package.json
chore: upgrade to latest version of Next.js and use turbopack build
**ITS TURBO TIME**
https://nextjs.org/blog/next-15-3
> [Build performance](https://nextjs.org/blog/next-15-3#build-performance)
> We’ve been validating Turbopack on Vercel’s large internal monorepo and early partner codebases. One advantage of Turbopack’s architecture versus our previous Webpack implementation is that performance scales when adding CPU cores:
> 
> At 4 cores: 28% faster than Webpack
> At 16 cores: 60% faster than Webpack
> At 30 cores: 83% faster than Webpack
> These build times drop even further with our experimental work on persistent caching. We will share more on that in a future release.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including …
=> chore: upgrade to latest version of Next.js and use turbopack build

README.md
Updated the readme to explain our current use of Flagsmith feature flags.
---
=> feat: Add notes about Flagsmith to readme

src/api/ParticipantManager.Shared/Client/FeatureFlagClient.cs, tests/ParticipantManager.Shared.Tests/Client/FeatureFlagClientTests.cs
Added default value to handle flagsmith API exception 
---
=> feat: Flagsmith default value fallback

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml, .azuredevops/pipelines/cd-infrastructure-dev-core.yaml, .github/workflows/cicd-1-pull-request.yaml, infrastructure/tf-audit/outputs.tf, infrastructure/tf-audit/providers.tf, infrastructure/tf-core/app_service_plan.tf, infrastructure/tf-core/data.tf, infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/int.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/providers.tf, infrastructure/tf-core/variables.tf, infrastructure/tf-core/web_app.tf, src/api/ParticipantManager.Shared/delete_me
- Custom Domain and certificate bindings for Azure Web Apps. Certificate registration with the App Service Plan isn't currently working (suspect an exemption for Public network access to Hub Key Vault may be needed from CCOE), but beyond that manual step the rest is automated, including the public DNS challenge in the Hub.
- Azure SQL log storage account RBAC roles are no longer reset every pipeline run.
- Application Insights is now configured via reference to each environment's Audit terraform state, rather than by parameterisation.
This change has proved complex, since the SSL certificates exist as entities within the App Service Plan which is a separate Terraform module from the Azure Web App module. The certificate being loaded on also originates in a different Terraform state and …
=> feat: DTOSS-8363 Web App custom domain support

compose.yaml, nginx/nginx.conf
- Added all required frontend environment variables
- Added nginx container for HTTPS on frontend
- Updated CRUD_API_URL environment variable for event handler container
- Couldn't get past login on frontend container
- Event handler container could not reach the backend api container
---
=> build: docker compose frontend and event handler fixes

infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/int.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/function_app.tf, infrastructure/tf-core/variables.tf, infrastructure/tf-core/web_app.tf
- Remove redundant parameterisation for `var.public_dns_zone_rg_name`, in favour of an output from the Hub state.
- App Insights has been configured by outputs from Hub also, some `.tfvars` files contained stale config for this.
- Improved structure of environment variable config for Function App and Web App, for comprehension.
Successful plan with no changes in Dev (no functional impact):
https://dev.azure.com/nhse-dtos/dtos-participant-manager/_build/results?buildId=18188&view=results
Reduce the chance of configuration error in future when building the additional environments (this string value changes in non-live/live).
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID …
=> fix: Remove some redundant parameterisation in Terraform

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml, .azuredevops/pipelines/cd-infrastructure-int-core.yaml, .azuredevops/pipelines/cd-infrastructure-nft-audit.yaml, .azuredevops/pipelines/cd-infrastructure-nft-core.yaml, .azuredevops/pipelines/cd-infrastructure-prd-audit.yaml, .azuredevops/pipelines/cd-infrastructure-prd-core.yaml, .azuredevops/pipelines/cd-infrastructure-pre-audit.yaml, .azuredevops/pipelines/cd-infrastructure-pre-core.yaml
ADO deployment pipelines for new Participant Manager environments.
---
=> feat: DTOS-8955 Add pipelines for new environments

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml, .azuredevops/pipelines/cd-infrastructure-dev-core.yaml, .azuredevops/pipelines/cd-infrastructure-int-audit.yaml, .azuredevops/pipelines/cd-infrastructure-int-core.yaml, .azuredevops/pipelines/cd-infrastructure-nft-audit.yaml, .azuredevops/pipelines/cd-infrastructure-nft-core.yaml, .azuredevops/pipelines/cd-infrastructure-prd-audit.yaml, .azuredevops/pipelines/cd-infrastructure-prd-core.yaml, .azuredevops/pipelines/cd-infrastructure-pre-audit.yaml, .azuredevops/pipelines/cd-infrastructure-pre-core.yaml, infrastructure/tf-core/web_app.tf
Fix a warning about an implicit provider in linux-web-app module, now explicitly named in the module template.
---
=> fix: Multiple providers in module warning
